### PR TITLE
Single cam

### PR DESCRIPTION
**Pull request by iandobbie**
This pull request allows one or two cameras to be specified on the command line, generating an interface with one or two cameras. 

Needs the help text clarified but I am confused as to why we have both default help text and argparser generating help text. should we not just get rid of the defualt text?

### CODE REVIEW

**Comment by iandobbie** [comment]
Removed additional help text printing and added some additional info to the argparser help text so we don't have redundant info or even get two lots of help text in some circumstances.

**Comment by carandraug** [comment]
In the middle of this commits there was a change that change the font size for 18. If the point is to make it slightly larger than the default, then I think it's better we do it by increasing the default size (which is system dependent) instead of setting it to 18. I have done that now with 592872fafc14441b30

Issue #4 talks about one, two, or more cameras but the fix proposed here only adds the option for one or two. The branch multi-cameras on my fork adds the option to use any positive number of cameras.

**Comment by iandobbie** [comment]
The font size was particularly on the difference values as you might want to see them from some distance away. Can we just make this text bigger while leaving the rest up to the window theme?

What are peoples thought on the help text. I realise we need to cherry-pick (or hand edit) the changes back in given David's improvement of the camera numbers issue. I think we should just have them in argparser but the original text needs a bit of expansion.

**Comment by carandraug** [comment]
> The font size was particularly on the difference values as you might want to see them from some distance away. Can we just make this text bigger while leaving the rest up to the window theme?

That's what I did. I increased the size of that text only, but by multiplying its default size by 1.5 (instead of setting to 18). Otherwise, say someone has set its system font size to 20. By manually setting it to 18, we were actually making it smaller.

> What are peoples thought on the help text. I realise we need to cherry-pick (or hand edit) the changes back in given David's improvement of the camera numbers issue. I think we should just have them in argparser but the original text needs a bit of expansion.

If we want to expand them, argparse has description and epilog sections. Maybe those can be used?

Anyway, the purpose of this PR was the single cam which is now fixed in another way. So closing this.

**Pull request closed without merging**
